// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protosTypes from '../protos/protos';
import * as assert from 'assert';
import {describe, it} from 'mocha';
const bigtableModule = require('../src');

import {PassThrough} from 'stream';

const FAKE_STATUS_CODE = 1;
class FakeError {
  name: string;
  message: string;
  code: number;
  constructor(n: number) {
    this.name = 'fakeName';
    this.message = 'fake message';
    this.code = n;
  }
}
const error = new FakeError(FAKE_STATUS_CODE);
export interface Callback {
  (err: FakeError | null, response?: {} | null): void;
}

export class Operation {
  constructor() {}
  promise() {}
}
function mockSimpleGrpcMethod(
  expectedRequest: {},
  response: {} | null,
  error: FakeError | null
) {
  return (actualRequest: {}, options: {}, callback: Callback) => {
    assert.deepStrictEqual(actualRequest, expectedRequest);
    if (error) {
      callback(error);
    } else if (response) {
      callback(null, response);
    } else {
      callback(null);
    }
  };
}
function mockServerStreamingGrpcMethod(
  expectedRequest: {},
  response: {} | null,
  error: FakeError | null
) {
  return (actualRequest: {}) => {
    assert.deepStrictEqual(actualRequest, expectedRequest);
    const mockStream = new PassThrough({
      objectMode: true,
      transform: (chunk: {}, enc: {}, callback: Callback) => {
        if (error) {
          callback(error);
        } else {
          callback(null, response);
        }
      },
    });
    return mockStream;
  };
}
describe('v2.BigtableClient', () => {
  it('has servicePath', () => {
    const servicePath = bigtableModule.v2.BigtableClient.servicePath;
    assert(servicePath);
  });
  it('has apiEndpoint', () => {
    const apiEndpoint = bigtableModule.v2.BigtableClient.apiEndpoint;
    assert(apiEndpoint);
  });
  it('has port', () => {
    const port = bigtableModule.v2.BigtableClient.port;
    assert(port);
    assert(typeof port === 'number');
  });
  it('should create a client with no option', () => {
    const client = new bigtableModule.v2.BigtableClient();
    assert(client);
  });
  it('should create a client with gRPC fallback', () => {
    const client = new bigtableModule.v2.BigtableClient({
      fallback: true,
    });
    assert(client);
  });
  it('has initialize method and supports deferred initialization', async () => {
    const client = new bigtableModule.v2.BigtableClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    assert.strictEqual(client.bigtableStub, undefined);
    await client.initialize();
    assert(client.bigtableStub);
  });
  it('has close method', () => {
    const client = new bigtableModule.v2.BigtableClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.close();
  });
  describe('mutateRow', () => {
    it('invokes mutateRow without error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IMutateRowRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.mutateRow = mockSimpleGrpcMethod(
        request,
        expectedResponse,
        null
      );
      client.mutateRow(request, (err: {}, response: {}) => {
        assert.ifError(err);
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
    });

    it('invokes mutateRow with error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IMutateRowRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.mutateRow = mockSimpleGrpcMethod(
        request,
        null,
        error
      );
      client.mutateRow(request, (err: FakeError, response: {}) => {
        assert(err instanceof FakeError);
        assert.strictEqual(err.code, FAKE_STATUS_CODE);
        assert(typeof response === 'undefined');
        done();
      });
    });
  });
  describe('checkAndMutateRow', () => {
    it('invokes checkAndMutateRow without error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.ICheckAndMutateRowRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.checkAndMutateRow = mockSimpleGrpcMethod(
        request,
        expectedResponse,
        null
      );
      client.checkAndMutateRow(request, (err: {}, response: {}) => {
        assert.ifError(err);
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
    });

    it('invokes checkAndMutateRow with error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.ICheckAndMutateRowRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.checkAndMutateRow = mockSimpleGrpcMethod(
        request,
        null,
        error
      );
      client.checkAndMutateRow(request, (err: FakeError, response: {}) => {
        assert(err instanceof FakeError);
        assert.strictEqual(err.code, FAKE_STATUS_CODE);
        assert(typeof response === 'undefined');
        done();
      });
    });
  });
  describe('readModifyWriteRow', () => {
    it('invokes readModifyWriteRow without error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IReadModifyWriteRowRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.readModifyWriteRow = mockSimpleGrpcMethod(
        request,
        expectedResponse,
        null
      );
      client.readModifyWriteRow(request, (err: {}, response: {}) => {
        assert.ifError(err);
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
    });

    it('invokes readModifyWriteRow with error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IReadModifyWriteRowRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.readModifyWriteRow = mockSimpleGrpcMethod(
        request,
        null,
        error
      );
      client.readModifyWriteRow(request, (err: FakeError, response: {}) => {
        assert(err instanceof FakeError);
        assert.strictEqual(err.code, FAKE_STATUS_CODE);
        assert(typeof response === 'undefined');
        done();
      });
    });
  });
  describe('readRows', () => {
    it('invokes readRows without error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IReadRowsRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.readRows = mockServerStreamingGrpcMethod(
        request,
        expectedResponse,
        null
      );
      const stream = client.readRows(request);
      stream.on('data', (response: {}) => {
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
      stream.on('error', (err: FakeError) => {
        done(err);
      });
      stream.write();
    });
    it('invokes readRows with error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IReadRowsRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.readRows = mockServerStreamingGrpcMethod(
        request,
        null,
        error
      );
      const stream = client.readRows(request);
      stream.on('data', () => {
        assert.fail();
      });
      stream.on('error', (err: FakeError) => {
        assert(err instanceof FakeError);
        assert.strictEqual(err.code, FAKE_STATUS_CODE);
        done();
      });
      stream.write();
    });
  });
  describe('sampleRowKeys', () => {
    it('invokes sampleRowKeys without error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.ISampleRowKeysRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.sampleRowKeys = mockServerStreamingGrpcMethod(
        request,
        expectedResponse,
        null
      );
      const stream = client.sampleRowKeys(request);
      stream.on('data', (response: {}) => {
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
      stream.on('error', (err: FakeError) => {
        done(err);
      });
      stream.write();
    });
    it('invokes sampleRowKeys with error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.ISampleRowKeysRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.sampleRowKeys = mockServerStreamingGrpcMethod(
        request,
        null,
        error
      );
      const stream = client.sampleRowKeys(request);
      stream.on('data', () => {
        assert.fail();
      });
      stream.on('error', (err: FakeError) => {
        assert(err instanceof FakeError);
        assert.strictEqual(err.code, FAKE_STATUS_CODE);
        done();
      });
      stream.write();
    });
  });
  describe('mutateRows', () => {
    it('invokes mutateRows without error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IMutateRowsRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.mutateRows = mockServerStreamingGrpcMethod(
        request,
        expectedResponse,
        null
      );
      const stream = client.mutateRows(request);
      stream.on('data', (response: {}) => {
        assert.deepStrictEqual(response, expectedResponse);
        done();
      });
      stream.on('error', (err: FakeError) => {
        done(err);
      });
      stream.write();
    });
    it('invokes mutateRows with error', done => {
      const client = new bigtableModule.v2.BigtableClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      // Initialize client before mocking
      client.initialize();
      // Mock request
      const request: protosTypes.google.bigtable.v2.IMutateRowsRequest = {};
      request.tableName = '';
      // Mock response
      const expectedResponse = {};
      // Mock gRPC layer
      client._innerApiCalls.mutateRows = mockServerStreamingGrpcMethod(
        request,
        null,
        error
      );
      const stream = client.mutateRows(request);
      stream.on('data', () => {
        assert.fail();
      });
      stream.on('error', (err: FakeError) => {
        assert(err instanceof FakeError);
        assert.strictEqual(err.code, FAKE_STATUS_CODE);
        done();
      });
      stream.write();
    });
  });
});
