// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import {before, describe, it} from 'mocha';
import {Bigtable} from '../src';
import * as assert from 'assert';

import {GoogleError} from 'google-gax';
import {MockServer} from '../src/util/mock-servers/mock-server';
import {BigtableClientMockService} from '../src/util/mock-servers/service-implementations/bigtable-client-mock-service';
import {MockService} from '../src/util/mock-servers/mock-service';

// TODO: Test server shuts down

describe('Bigtable/Grpc-mock', () => {
  const server: MockServer = new MockServer();

  describe('with the bigtable data client', () => {
    const service: MockService = new BigtableClientMockService(server);

    describe('sends errors through a streaming request', () => {
      const errorDetails =
        'Table not found: projects/my-project/instances/my-instance/tables/my-table';
      const emitTableNotExistsError = (stream: any) => {
        // TODO: Replace stream with type
        stream.emit('error', {
          code: 5,
          details: errorDetails,
        });
      };
      describe('with ReadRows service', () => {
        before(async () => {
          service.setService({
            ReadRows: emitTableNotExistsError,
          });
        });
        it('should produce human readable error when passing through gax', done => {
          const bigtable = new Bigtable({apiEndpoint: 'localhost:1234'});
          const table = bigtable.instance('fake-instance').table('fake-table');
          const readStream = table.createReadStream({});
          readStream.on('error', (err: GoogleError) => {
            const {code, statusDetails, message} = err;
            assert.strictEqual(statusDetails, errorDetails);
            assert.strictEqual(code, 5);
            assert.strictEqual(
              message,
              '5 NOT_FOUND: Table not found: projects/my-project/instances/my-instance/tables/my-table'
            );
            done();
          });
        });
      });
      describe('with mutateRows service through insert', () => {
        before(async () => {
          service.setService({
            mutateRows: emitTableNotExistsError,
          });
        });
        it('should produce human readable error when passing through gax', async () => {
          const bigtable = new Bigtable({apiEndpoint: 'localhost:1234'});
          const table = bigtable.instance('fake-instance').table('fake-table');
          const timestamp = new Date();
          const rowsToInsert = [
            {
              key: 'r2',
              data: {
                cf1: {
                  c1: {
                    value: 'test-value2',
                    labels: [],
                    timestamp,
                  },
                },
              },
            },
          ];
          try {
            await table.insert(rowsToInsert);
            assert.fail();
          } catch (err) {
            const {code, statusDetails, message} = err;
            assert.strictEqual(statusDetails, errorDetails);
            assert.strictEqual(code, 5);
            assert.strictEqual(
              message,
              '5 NOT_FOUND: Table not found: projects/my-project/instances/my-instance/tables/my-table'
            );
          }
        });
      });
      describe('with sampleRowKeys', () => {
        before(async () => {
          service.setService({
            sampleRowKeys: emitTableNotExistsError,
          });
        });
        it('should produce human readable error when passing through gax', async () => {
          const bigtable = new Bigtable({apiEndpoint: 'localhost:1234'});
          const table = bigtable.instance('fake-instance').table('fake-table');
          try {
            await table.sampleRowKeys({});
            assert.fail();
          } catch (err) {
            const {code, statusDetails, message} = err;
            assert.strictEqual(statusDetails, errorDetails);
            assert.strictEqual(code, 5);
            assert.strictEqual(
              message,
              '5 NOT_FOUND: Table not found: projects/my-project/instances/my-instance/tables/my-table'
            );
          }
        });
      });
    });
  });
});
