// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import {grpc} from 'google-gax';
import {SameCallHandler} from './same-call-handler';
import {MockService} from '../../../mock-service';
import {Row} from '../../../../../row';

export class SendErrorHandler extends SameCallHandler {
  code: grpc.status;
  request: any = null;
  callCount = 0;
  message: any;

  // TODO: service and endpoint should be bundled into one object.
  constructor(
    service: MockService,
    endpoint: string,
    code: grpc.status,
    message?: any
  ) {
    super(service, endpoint);
    this.code = code;
    this.message = Object.assign({}, message);
  }

  callHandler(call: any) {
    call.emit('error', {
      code: this.code,
      details: 'Details for a particular type of error',
    });
  }

  addData(data: string) {
    const lastIndex = this.data.length - 1;
    this.data[lastIndex].push(data);
  }

  snapshot(results: any): any {
    return {
      input: Object.assign(
        {code: this.code},
        this.message ? {message: this.message} : null
      ),
      output: {
        results,
        requestData: this.requests(),
      },
    };
  }
}
