// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

export abstract class ServiceHandler {
  /*
  callHandler accepts a grpc call and provides behaviour for that grpc call
  which may involve sending errors or data back to the client for
  example.
  */
  abstract callHandler(call: any): void;

  /*
  snapshotOutput is used to provide a custom json object that represents the
  results of the test that was run with this service handler.
   */
  abstract snapshot(results: any): any;

  /*
  setupService is called to setup the service we use for collecting data about
  a running test.
   */
  abstract setupService(): void;

  /*
  addData is called to add data which will be reported in the snapshot later on.
   */
  abstract addData(data: string): void;

  /*
  getData is called to get all data which was collected from requests.
   */
  abstract getData(): string[][];
}
