// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

export const testGaxOptions = {
  timeout: 1000,
  retry: {
    retryCodes: [3, 5, 7, 12],
    backoffSettings: {
      maxRetries: 41,
      initialRetryDelayMillis: 401,
      retryDelayMultiplier: 42,
      maxRetryDelayMillis: 402,
      initialRpcTimeoutMillis: 403,
      maxRpcTimeoutMillis: 404,
      rpcTimeoutMultiplier: 43,
    },
  },
  autoPaginate: true,
  maxResults: 23,
  maxRetries: 24,
  otherArgs: {
    otherArg1: 217,
  },
  bundleOptions: {
    elementCountLimit: 71,
    requestByteLimit: 72,
    elementCountThreshold: 73,
    requestByteThreshold: 74,
    delayThreshold: 75,
  },
  isBundling: false,
  longRunning: {
    maxRetries: 5,
    initialRetryDelayMillis: 501,
    retryDelayMultiplier: 52,
    maxRetryDelayMillis: 502,
    initialRpcTimeoutMillis: 503,
    maxRpcTimeoutMillis: 504,
    totalTimeoutMillis: 505,
    rpcTimeoutMultiplier: 53,
  },
  apiName: 'test-apiName',
  retryRequestOptions: {
    objectMode: true,
    request: 'test-request',
    retries: 38,
    noResponseRetries: 39,
    currentRetryAttempt: 35,
    shouldRetryFn: () => {
      return true;
    },
  },
};
